version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_gateway
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - sc_service
      - sekolah_service

  auth_service:
    image: auth_service_image
    container_name: auth_service
    ports:
      - "50051:50051"

  sc_service:
    image: sc_service_image
    container_name: sc_service
    ports:
      - "50052:50052"

  sekolah_service:
    image: sekolah_service_image
    container_name: sekolah_service
    ports:
      - "50053:50053"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
