version: "3.9"
services:
  auth_service:
    build:
      context: ./backend/auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  sekolah_service:
    build:
      context: ./backend/sekolah
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  smartcontract_service:
    build:
      context: ./backend/sc-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth_service
      - sekolah_service
      - smartcontract_service

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
