# Base image
FROM golang:1.22.3

# Set environment variables
ENV GO111MODULE=on
ENV GOPROXY=https://proxy.golang.org,direct

# Install air for hot reload
RUN go install github.com/cosmtrek/air@v1.43.0

# Set working directory
WORKDIR /app

# Copy go.mod, go.sum, dan dependensi lokal
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy seluruh source code
COPY . .

# Expose port gRPC
EXPOSE 50051

# Jalankan aplikasi dengan Air untuk hot reload
CMD ["air"]
