services:
  sc_db:
    image: postgres:15-alpine
    container_name: sc_db_container
    restart: always
    environment:
      POSTGRES_USER: ${SC_USER}
      POSTGRES_PASSWORD: ${SC_PASSWORD}
      POSTGRES_DB: ${SC_DB}
    ports:
      - "${SC_PORT}:5432"
    volumes:
      - sc_db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  # sc_redis:
  #   image: redis:alpine
  #   container_name: sc_redis_container
  #   restart: always
  #   ports:
  #     - "${SCREDIS_PORT}:6379"

volumes:
  sc_db_data:



# networks:
#   fabric_network:

# services:
#   orderer.example.com:
#     image: hyperledger/fabric-orderer:2.4
#     container_name: orderer.example.com
#     environment:
#       - FABRIC_LOGGING_SPEC=INFO
#       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#       - ORDERER_GENERAL_LISTENPORT=7050
#       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
#       - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
#     volumes:
#       - ./configtx/ordererGenesis.block:/var/hyperledger/orderer/orderer.block
#       - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
#       - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
#     ports:
#       - 7050:7050
#     networks:
#       - fabric_network

#   peer0.org1.example.com:
#     image: hyperledger/fabric-peer:2.4
#     container_name: peer0.org1.example.com
#     environment:
#       - CORE_PEER_ID=peer0.org1.example.com
#       - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
#       - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
#       - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
#       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
#       - CORE_PEER_LOCALMSPID=Org1MSP
#       - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
#     volumes:
#       - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/peer/msp
#       - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/peer/tls
#     ports:
#       - 7051:7051
#     depends_on:
#       - orderer.example.com
#     networks:
#       - fabric_network

#   ca.org1.example.com:
#     image: hyperledger/fabric-ca:1.5
#     container_name: ca.org1.example.com
#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-org1
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
#       - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
#     ports:
#       - 7054:7054
#     volumes:
#       - ./crypto-config/peerOrganizations/org1.example.com/ca:/etc/hyperledger/fabric-ca-server-config
#     networks:
#       - fabric_network


