version: '3.8'
services:
  sc_db:
    image: postgres:15-alpine
    container_name: sc_db_container
    restart: always
    environment:
      POSTGRES_USER: ${SC_USER}
      POSTGRES_PASSWORD: ${SC_PASSWORD}
      POSTGRES_DB: ${SC_DB}
    ports:
      - "${SC_PORT}:5432"
    volumes:
      - sc_db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  sc_redis:
    image: redis:alpine
    container_name: sc_redis_container
    restart: always
    ports:
      - "${SCREDIS_PORT}:6379"

volumes:
  sc_db_data:
