-- CREATE TABLE IF NOT EXISTS blockchain_platform (
-- 	"id" UUID NOT NULL,
-- 	"nm_blockchain" VARCHAR(50) NOT NULL,
-- 	"active" BOOLEAN NULL DEFAULT 'false',
-- 	"created_at" TIMESTAMP NULL DEFAULT 'now()',
-- 	"updated_at" TIMESTAMP NULL DEFAULT 'now()',
-- 	PRIMARY KEY ("id")
-- );
-- Tabel schema_logs
CREATE TABLE schema_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NULL,
    updated_at TIMESTAMPTZ DEFAULT NULL,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    schema_name TEXT DEFAULT NULL
);

CREATE INDEX idx_schema_logs_deleted_at ON schema_logs (deleted_at);

-- Tabel sekolah_tenants
CREATE TABLE sekolah_tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NULL,
    updated_at TIMESTAMPTZ DEFAULT NULL,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    nama_sekolah TEXT DEFAULT NULL,
    user_id INTEGER DEFAULT NULL,
    sekolah_id INTEGER DEFAULT NULL,
    schema_name TEXT NOT NULL,
    CONSTRAINT uni_sekolah_tenants_schema_name UNIQUE (schema_name)
);

CREATE INDEX idx_sekolah_tenants_deleted_at ON sekolah_tenants (deleted_at);

CREATE TABLE IF NOT EXISTS ijazah_bc (
    id UUID PRIMARY KEY,
    peserta_didik_id UUID NOT NULL,
    nama VARCHAR(255),
    nis VARCHAR(50),
    nisn VARCHAR(50),
    npsn VARCHAR(50),
    nomor_ijazah VARCHAR(100),
    tempat_lahir VARCHAR(100),
    tanggal_lahir DATE,
    nama_ortuwali VARCHAR(255),
    paket_keahlian VARCHAR(255),
    kabupatenkota VARCHAR(100),
    provinsi VARCHAR(100),
    program_keahlian VARCHAR(255),
    sekolah_penyelenggara_ujian_us VARCHAR(255),
    sekolah_penyelenggara_ujian_un VARCHAR(255),
    asal_sekolah VARCHAR(255),
    tempat_ijazah VARCHAR(100),
    tanggal_ijazah DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS degree_data (
    id SERIAL PRIMARY KEY,
    ijazah_id UUID NOT NULL,
    degree_hash VARCHAR(255),
    tx_hash VARCHAR(255),
    ipfs_url TEXT,
    bc_type VARCHAR(50),
    link_bc_explorer TEXT,
    sekolah_id UUID NOT NULL,
    tahun_ajaran_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ijazah FOREIGN KEY (ijazah_id) REFERENCES ijazah_bc(id) ON UPDATE CASCADE ON DELETE CASCADE
);



