version: '3.6'
services:
  node1:
    image: quorumengineering/quorum:24.4.1
    container_name: node_sekolah
    ports:
      - "22000:8545"
      - "21000:30303"
    volumes:
      - ./node1/data:/quorum
      - ./node1/static-nodes.json:/quorum/static-nodes.json
      - ./node1/nodekey:/quorum/nodekey
    environment:
      - PRIVATE_CONFIG=ignore
    command: >
      sh -c "
      geth --datadir=/quorum init /config/genesis.json;
      geth --datadir=/quorum --nodiscover --verbosity 5 --networkid 1337 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints
      "

  # node2:
    # image: quorumengineering/quorum:24.4.1
    # container_name: node_dinas_pendidikan
    # ports:
      # - "22001:8545"
      # - "21001:30303"
    # volumes:
      # - ./node2/data:/quorum
      # - ./node2/static-nodes.json:/quorum/static-nodes.json
      # - ./node2/nodekey:/quorum/nodekey
    # environment:
      # - PRIVATE_CONFIG=ignore
    # command: --datadir /quorum --nodiscover --verbosity 5 --networkid 1337 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints

  # node3:
    # image: quorumengineering/quorum:24.4.1
    # container_name: node_lembaga_penjamin_mutu
    # ports:
      # - "22002:8545"
      # - "21002:30303"
    # volumes:
      # - ./node3/data:/quorum
      # - ./node3/static-nodes.json:/quorum/static-nodes.json
      # - ./node3/nodekey:/quorum/nodekey
    # environment:
      # - PRIVATE_CONFIG=ignore
    # command: --datadir /quorum --nodiscover --verbosity 5 --networkid 1337 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints